//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationEvent
    {
        public int AssociationEvent_ID { get; set; }
        public string AssociationEvent_Title { get; set; }
        public string AssociationEvent_Detail { get; set; }
        public string AssociationEvent_Year { get; set; }
        public string AssociationEvent_Picture { get; set; }
        public string AssociationEvent_Modifier { get; set; }
        public Nullable<System.TimeSpan> AssociationEvent_ModificationTime { get; set; }
        public Nullable<System.DateTime> AssociationEvent_ModificationDate { get; set; }
        public int Member_ID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
